language: elixir
elixir:
  - 1.1.1
  - 1.2.5
otp_release:
  - 18.2.1
sudo: false
install: true
addons:
  apt:
    packages:
    - automake
    - bison
    - flex
    - g++
    - libboost-dev
    - libboost-test-dev
    - libboost-program-options-dev
    - libevent-dev
    - libtool
    - libssl-dev
    - pkg-config
before_script:
  - mix local.hex --force
script:
  - git submodule init
  - git submodule update
  - MIX_ENV=test mix do deps.get, compile
after_script:
  - MIX_ENV=test mix coveralls.travis
cache:
  directories:
  - $HOME/.mix/archives
